name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_iterations: 10
          allowed_tools: |
            bash
            gh_cli
          custom_instructions: |
            You have access to the GitHub CLI (gh) command. 
            When asked to create a pull request, use: gh pr create
            The GH_TOKEN is already configured.
            You can run bash commands to execute git and gh operations.